### ISSUE TITLE
How does http2dotnet relate to the upcoming http2 support in dotnet?

### ISSUE THREAD

**Issue by copernicus365** [Matthias247/http2dotnet#2]
This library is clearly a *huge* amount of hard and impressive work, bravo! Even the documentation on the readme page, I could only wish more libraries were like this.

That said, before investing work into this, I am wondering how http2dotnet relates to the new (or upcoming) http2 support within the dotnet stack? And will some of this http2dotnet work be replaced by components now in the dotnet stack? (Or maybe even was some of this used as pull requests for that? I wouldn't be surprised).

I just need to know where I should invest my time, especially since I am a novice in networking / sockets / and other low-level networking stuff. My context is hoping to figure out how to send notifications to iOS using their newer http/2 api. 

Thanks!

**Comment by Matthias247** [comment]
Honestly - I can't tell you. I haven't followed the official .NET development for the last month. If you would have a link where it gets implemented I would be interested too :-)

The last time looked mid of last year there was only the start of an implementation inside Kestrel (for ASP.Net Core). That one lacked most of the important HTTP/2 features (e.g. flow-control), while this library is already complete.
Microsoft could have built their solution on top of this library (and some people there should be aware of it), but I guess for whatever reasons they wanted to have something developed in-house.

I don't think this library would be obsoleted by an official solution, since an official one would probably work on a higher level: Either as a complete HTTP/2 client (which might already exist in .NET Core on top of libcurl) or as a complete Webserver (on top of ASP.Net).
The library here is lower level, and can be used to either build a client or a webserver. Or something completely different which uses the HTTP/2 stream mechanism under the hood, like gRPC.
As far as I understand it should also work for the iOS push notifications, but I haven't experimented with that. And I have to say upfront that I can't give a lot of support, since I'm currently being busy with other tasks. However the implementation should mostly work, and the test coverage is pretty big.
